#!/bin/sh

config_file="${XDG_CONFIG_HOME:-$HOME/.config}/keepmenu-sh/config"

sed_escape() {
    sed -e 's/[]\/$*.^[]/\\&/g'
}

cfg_read() { # path, key -> value
    test -f "$1" && grep "^$(echo "$2" | sed_escape)=" "$1" | sed "s/^$(echo "$2" | sed_escape)=//" | tail -1
}

cfg_write() { # path, key, value
    echo "$2=$3" >> "$1"
}

if [ ! -f $config_file ]; then
    printf "No configuration file found\n%s\nPlease edit the file and provide the appropriate values\n" "Creating template in $config_file"
    mkdir -p "${XDG_CONFIG_HOME:-$HOME/.config}/keepmenu-sh"
    cfg_write "$config_file" db_path
    cfg_write "$config_file" key_path
    cfg_write "$config_file" dmenu_flags
    exit 1
fi

db_path=$(cfg_read $config_file db_path)
key_path=$(cfg_read $config_file key_path)
dmenu_flags=$(cfg_read $config_file dmenu_flags)

[ -z "$db_path" ] && echo "Missing configuration option 'db_path'" && exit 1
[ -z "$key_path" ] && echo "Missing configuration option 'key_path'" && exit 1

# dmenu prompt
prompt="copy password:"

# get all entries from the db
not_found=0
db_entries=$(keepassxc-cli ls -R -f "$db_path" -k "$key_path" --no-password | grep '/$' -v) || not_found=1
if [ "$not_found" -eq 1 ]; then
    printf "Provide the absolute path for the database and the key in the config file\n"
    exit 1
fi

# pipe the list into dmenu to show the password picker
entry=$(printf '%s\n' "$db_entries" | dmenu $dmenu_flags -p "$prompt" "$@") || exit

# copy the selected entrys password to the clipboard
keepassxc-cli clip ~/passwords.kdbx -k ~/keepassxc-key --no-password "$entry"
